"""initial schema

Revision ID: 0001
Revises: Nicolas Castaneda
Create Date: 2026-05-07 00:26:39.258791+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ed33db2485'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_price_reports',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('products_analyzed', sa.Integer(), nullable=False),
    sa.Column('avg_drift_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('alerts_critical', sa.Integer(), nullable=False),
    sa.Column('alerts_medium', sa.Integer(), nullable=False),
    sa.Column('alerts_low', sa.Integer(), nullable=False),
    sa.Column('fx_rate_usd_clp_avg', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('fx_rate_usd_mxn_avg', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('fx_rate_usd_cop_avg', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('report_date'),
    schema='app'
    )
    op.create_table('fx_rates',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_minute', sa.DateTime(), sa.Computed("date_trunc('minute', captured_at AT TIME ZONE 'UTC')", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('base_currency', 'quote_currency', 'captured_minute', name='pk_fx_rates'),
    schema='app'
    )
    op.create_index('ix_fx_rates_captured_at', 'fx_rates', ['captured_at'], unique=False, schema='app')
    op.create_table('products',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_price_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sku'),
    schema='app'
    )
    op.create_table('stores',
    sa.Column('store_id', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    schema='app'
    )
    op.create_table('api_health_log',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=16), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['app.stores.store_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='app'
    )
    op.create_index('ix_api_health_log_captured_at', 'api_health_log', ['captured_at'], unique=False, schema='app')
    op.create_table('price_alerts',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('avg_local_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('avg_price_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('canonical_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('drift_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cause_hint', sa.String(length=32), nullable=False),
    sa.CheckConstraint("cause_hint IN ('fx_movement', 'manual_change', 'mixed', 'unknown')", name='ck_price_alerts_cause_hint'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'critical')", name='ck_price_alerts_severity'),
    sa.ForeignKeyConstraint(['sku'], ['app.products.sku'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['app.stores.store_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('report_date', 'store_id', 'sku', name='pk_price_alerts'),
    schema='app'
    )
    op.create_index('ix_price_alerts_report_date', 'price_alerts', ['report_date'], unique=False, schema='app')
    op.create_table('price_change_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('prev_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pct_change', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['app.products.sku'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['app.stores.store_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('store_id', 'sku', 'detected_at', name='uq_price_change_events'),
    schema='app'
    )
    op.create_index('ix_price_change_events_detected_at', 'price_change_events', ['detected_at'], unique=False, schema='app')
    op.create_table('price_snapshots',
    sa.Column('store_id', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('local_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_status', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_minute', sa.DateTime(), sa.Computed("date_trunc('minute', captured_at AT TIME ZONE 'UTC')", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['app.products.sku'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['app.stores.store_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('store_id', 'sku', 'captured_minute', name='pk_price_snapshots'),
    schema='app'
    )
    op.create_index('ix_price_snapshots_captured_at', 'price_snapshots', ['captured_at'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_snapshots_captured_at', table_name='price_snapshots', schema='app')
    op.drop_table('price_snapshots', schema='app')
    op.drop_index('ix_price_change_events_detected_at', table_name='price_change_events', schema='app')
    op.drop_table('price_change_events', schema='app')
    op.drop_index('ix_price_alerts_report_date', table_name='price_alerts', schema='app')
    op.drop_table('price_alerts', schema='app')
    op.drop_index('ix_api_health_log_captured_at', table_name='api_health_log', schema='app')
    op.drop_table('api_health_log', schema='app')
    op.drop_table('stores', schema='app')
    op.drop_table('products', schema='app')
    op.drop_index('ix_fx_rates_captured_at', table_name='fx_rates', schema='app')
    op.drop_table('fx_rates', schema='app')
    op.drop_table('daily_price_reports', schema='app')
    # ### end Alembic commands ###
